### ISSUE TITLE
nosedep:NoseDep: cannot import name windows_support - setuptools 37

### ISSUE THREAD

**Issue by iyaozhen** [Zitrax/nose-dep#11]
When I use python 2.7.14 and upgrade setuptools from 36.5 to 37
```
pip install nose
pip install nosedep
```
```
nosetests -V
python2.7/site-packages/nose/plugins/manager.py:395: RuntimeWarning: 
Unable to load plugin nosedep = nosedep:NoseDep: cannot import name windows_support 
 RuntimeWarning)
nosetests version 1.3.7
```
setuptools 36.5 or other nose plugin work well

**Comment by Zitrax** [comment]
Hi sorry for late answer. I have not encountered this issue but I can see if I can reproduce it.

**Comment by iyaozhen** [comment]
more information, I use Mac, and `brew install python`

**Comment by Zitrax** [comment]
Unfortunately I do not have access to a Mac, I did a try on Linux now and it worked fine there with python 2.7.12 and setuptools 38.2.4.

nosetests -V

    nosetests version 1.3.7

Nosedep does not directly import window_support. Grepping for that it appears in the setuptools source. Could it be a setuptools issue rather than a nosedep one ? Setuptools should have a file windows_support.py.
